# Site settings
title: scratchpad
description: Collection of notes
timezone: America/Toronto

baseurl: "/scratchpad" # the subpath of your site, e.g. /blog/
url: "http://vadimbrodsky.github.io/scratchpad" # the base hostname & protocol for your site
permalink: notes/:categories/:title/

email: vadim.brodsky@gmail.com
twitter_username: vadimbrodsky
github_username:  vadimbrodsky


# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]


# Collections
collections:
  snippets:
    output: true


# Category Index Plugin
# https://github.com/shigeya/jekyll-category-archive-plugin
category_archive: category


# Rake tasks settings
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: subl
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/username.github.com/
