# Site settings
title: knowbase
email: vadim.brodsky@gmail.com
description: Collection of notes
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: vadimbrodsky
github_username:  vadimbrodsky
permalink: notes/:categories/:title/

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]


collections:
  snippets:
    output: true


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "notes" # a collection in your site, in plural form
    values:
      layout: "default"




post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: subl
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/username.github.com/
